### ISSUE TITLE
Error during import: "Invalid type for variable 'must_be_approved'"

### ISSUE THREAD

**Issue by myasnov1** [testit-tms/importers#33]
After a couple of succeeded imports I receive this error. What it's all about?
![image](https://user-images.githubusercontent.com/128713745/230015689-7cf50b47-26d5-4edf-9046-9acf46814e8e.png)

**Comment by rielyalkov** [comment]
Добрый день! Столкнулся с аналогичной проблемой, возникает в том случае, если к определенному набору автотестов, который уже ранее были выгружены добавляется новый, ранее не выгруженный в TestIT.
Иногда помогает повторная попытка выгрузки. 

При этом, по наблюдениям, ошибка падает именно на попытке выгрузить этот новый автотест.

Воспроизводится как локальной машине, так и в CI-среде, что существенно тормозит выкладку новых автотестов в TestIT.

Ниже прикладываю трейсбэк ошибки:

`INFO:Set result passed!
Traceback (most recent call last):
  File "/usr/local/bin/testit", line 8, in <module>
    sys.exit(console_main())
  File "/usr/local/lib/python3.10/site-packages/testit_importer_allure/__main__.py", line 21, in console_main
    importer.send_result()
  File "/usr/local/lib/python3.10/site-packages/testit_importer_allure/importer.py", line 62, in send_result
    autotest_id = self.__api_client.create_autotest(
  File "/usr/local/lib/python3.10/site-packages/testit_importer_allure/apiclient.py", line 63, in create_autotest
    response = self.__autotest_api.create_auto_test(auto_test_post_model=model)
  File "/usr/local/lib/python3.10/site-packages/testit_api_client/api/auto_tests_api.py", line 1821, in create_auto_test
    return self.create_auto_test_endpoint.call_with_http_info(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/testit_api_client/api_client.py", line 879, in call_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.10/site-packages/testit_api_client/api_client.py", line 421, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.10/site-packages/testit_api_client/api_client.py", line 226, in __call_api
    return_data = self.deserialize(
  File "/usr/local/lib/python3.10/site-packages/testit_api_client/api_client.py", line 332, in deserialize
    deserialized_data = validate_and_convert_types(
  File "/usr/local/lib/python3.10/site-packages/testit_api_client/model_utils.py", line 1582, in validate_and_convert_types
    converted_instance = attempt_convert_item(
  File "/usr/local/lib/python3.10/site-packages/testit_api_client/model_utils.py", line 1471, in attempt_convert_item
    raise conversion_exc
  File "/usr/local/lib/python3.10/site-packages/testit_api_client/model_utils.py", line 1462, in attempt_convert_item
    return deserialize_model(input_value, valid_class,
  File "/usr/local/lib/python3.10/site-packages/testit_api_client/model_utils.py", line 1376, in deserialize_model
    return model_class._new_from_openapi_data(**kw_args)
  File "/usr/local/lib/python3.10/site-packages/testit_api_client/model_utils.py", line 48, in wrapped_init
    return fn(_self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/testit_api_client/model_utils.py", line 371, in _new_from_openapi_data
    return cls._from_openapi_data(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/testit_api_client/model_utils.py", line 48, in wrapped_init
    return fn(_self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/testit_api_client/model/auto_test_model.py", line 265, in _from_openapi_data
    setattr(self, var_name, var_value)
  File "/usr/local/lib/python3.10/site-packages/testit_api_client/model_utils.py", line 189, in __setattr__
    self[attr] = value
  File "/usr/local/lib/python3.10/site-packages/testit_api_client/model_utils.py", line 510, in __setitem__
    self.set_attribute(name, value)
  File "/usr/local/lib/python3.10/site-packages/testit_api_client/model_utils.py", line 161, in set_attribute
    value = validate_and_convert_types(
  File "/usr/local/lib/python3.10/site-packages/testit_api_client/model_utils.py", line 1582, in validate_and_convert_types
    converted_instance = attempt_convert_item(
  File "/usr/local/lib/python3.10/site-packages/testit_api_client/model_utils.py", line [145](https://git.gateline.net/b2c/rzd-portal/frontend/angular-frontend/-/jobs/371130#L145)7, in attempt_convert_item
    raise get_type_error(input_value, path_to_item, valid_classes,
testit_api_client.exceptions.ApiTypeError: Invalid type for variable 'must_be_approved'. Required value type is bool and passed type was NoneType at ['received_data']['must_be_approved']`

**Comment by taipoxinous** [comment]
Закрываю issue за давностью проблемы
