### ISSUE TITLE
25.09 перестали отправляться результаты в TestIT

### ISSUE THREAD

**Issue by Wanyann** [testit-tms/importers#44]
25.09 перестали отправляться результаты в TestIT. Пробовал на различных конфигурациях у себя - результат одинаковый, отправка падает. 25 числа как раз были какие-то технические работы, подозреваю, что там и могло поломаться.
Стектрейс:
`Traceback (most recent call last):
  File "/usr/local/bin/testit", line 8, in <module>
    sys.exit(console_main())
  File "/usr/local/lib/python3.8/dist-packages/testit_importer_allure/__main__.py", line 21, in console_main
    importer.send_result()
  File "/usr/local/lib/python3.8/dist-packages/testit_importer_allure/importer.py", line 27, in send_result
    self.__set_test_run()
  File "/usr/local/lib/python3.8/dist-packages/testit_importer_allure/importer.py", line 99, in __set_test_run
    self.__testrun_id = self.__api_client.create_test_run(self.__project_id, test_run_name)
  File "/usr/local/lib/python3.8/dist-packages/testit_importer_allure/apiclient.py", line 42, in create_test_run
    response = self.__test_run_api.create_empty(test_run_v2_post_short_model=model)
  File "/usr/local/lib/python3.8/dist-packages/testit_api_client/api/test_runs_api.py", line 1665, in create_empty
    return self.create_empty_endpoint.call_with_http_info(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/testit_api_client/api_client.py", line 879, in call_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.8/dist-packages/testit_api_client/api_client.py", line 421, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.8/dist-packages/testit_api_client/api_client.py", line 226, in __call_api
    return_data = self.deserialize(
  File "/usr/local/lib/python3.8/dist-packages/testit_api_client/api_client.py", line 3[32](http://gita.nauka.local/project-testing-group/Aurora_Platform/-/jobs/142548#L32), in deserialize
    deserialized_data = validate_and_convert_types(
  File "/usr/local/lib/python3.8/dist-packages/testit_api_client/model_utils.py", line 1582, in validate_and_convert_types
    converted_instance = attempt_convert_item(
  File "/usr/local/lib/python3.8/dist-packages/testit_api_client/model_utils.py", line 1462, in attempt_convert_item
    return deserialize_model(input_value, valid_class,
  File "/usr/local/lib/python3.8/dist-packages/testit_api_client/model_utils.py", line 1[37](http://gita.nauka.local/project-testing-group/Aurora_Platform/-/jobs/142548#L37)6, in deserialize_model
    return model_class._new_from_openapi_data(**kw_args)
  File "/usr/local/lib/python3.8/dist-packages/testit_api_client/model_utils.py", line 48, in wrapped_init
    return fn(_self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/testit_api_client/model_utils.py", line 371, in _new_from_openapi_data
    return cls._from_openapi_data(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/testit_api_client/model_utils.py", line 48, in wrapped_init
    return fn(_self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/testit_api_client/model/test_run_v2_get_model.py", line 226, in _from_openapi_data
    setattr(self, var_name, var_value)
  File "/usr/local/lib/python3.8/dist-packages/testit_api_client/model_utils.py", line 189, in __setattr__
    self[attr] = value
  File "/usr/local/lib/python3.8/dist-packages/testit_api_client/model_utils.py", line 510, in __setitem__
    self.set_attribute(name, value)
  File "/usr/local/lib/python3.8/dist-packages/testit_api_client/model_utils.py", line 1[38](http://gita.nauka.local/project-testing-group/Aurora_Platform/-/jobs/142548#L38), in set_attribute
    raise ApiAttributeError(
testit_api_client.exceptions.ApiAttributeError: TestRunV2GetModel has no attribute 'attachments' at ['received_data']['attachments']`

**Comment by PavelButuzov** [comment]
Добрый день!
Импортер переведен на api-клиент 3.3 #45. Пожалуйста, обновите импортер до версии 1.4.
Благодарим за обращение!
