### ISSUE TITLE
Ошибка загрузки результатов прохождения теста, если в таковой помечен аннотацией "@Issue" из package io.qameta.allure

### ISSUE THREAD

**Issue by ABolikov** [testit-tms/importers#47]
Добрый день.
Была найдена ошибка загрузки результатов прохождения теста, если таковой помечен аннотацией "@Issue" из package io.qameta.allure

Установили планиг командой: `pip install testit-importer-allure`
Результат установки: Successfully installed testit-api-client-3.3.0 testit-importer-allure-1.4.0

При прохождении тестов которые используют аннотацию "@Issue", Allure в файл о результате прохождения записывает список объектов Links где для каждого элемента записывается "type" в виде "issue".
Пример: `
"links": [
    {
      "name": "TEST-1",
      "url": "https://jira.com/browse/TEST-1",
      "type": "issue"
    }
  ]`

Если для этих результатов попробовать воспользоваться плагином, будет выведена ошибка:
`Traceback (most recent call last):
  File "/usr/local/bin/testit", line 8, in <module>
    sys.exit(console_main())
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/testit_importer_allure/__main__.py", line 21, in console_main
    importer.send_result()
  File "/usr/local/lib/python3.11/site-packages/testit_importer_allure/importer.py", line 64, in send_result
    autotest_id = self.__api_client.create_autotest(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/testit_importer_allure/apiclient.py", line 62, in create_autotest
    response = self.__autotest_api.create_auto_test(create_auto_test_request=model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/testit_api_client/api/auto_tests_api.py", line 1970, in create_auto_test
    return self.create_auto_test_endpoint.call_with_http_info(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/testit_api_client/api_client.py", line 881, in call_with_http_info
    return self.api_client.call_api(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/testit_api_client/api_client.py", line 423, in call_api
    return self.__call_api(resource_path, method,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/testit_api_client/api_client.py", line 226, in __call_api
    return_data = self.deserialize(
                  ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/testit_api_client/api_client.py", line 334, in deserialize
    deserialized_data = validate_and_convert_types(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/testit_api_client/model_utils.py", line 1582, in validate_and_convert_types
    converted_instance = attempt_convert_item(
                         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/testit_api_client/model_utils.py", line 1471, in attempt_convert_item
    raise conversion_exc
  File "/usr/local/lib/python3.11/site-packages/testit_api_client/model_utils.py", line 1462, in attempt_convert_item
    return deserialize_model(input_value, valid_class,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/testit_api_client/model_utils.py", line 1376, in deserialize_model
    return model_class._new_from_openapi_data(**kw_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/testit_api_client/model_utils.py", line 48, in wrapped_init
    return fn(_self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/testit_api_client/model_utils.py", line 371, in _new_from_openapi_data
    return cls._from_openapi_data(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/testit_api_client/model_utils.py", line 48, in wrapped_init
    return fn(_self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/testit_api_client/model/auto_test_model.py", line 274, in _from_openapi_data
    setattr(self, var_name, var_value)
  File "/usr/local/lib/python3.11/site-packages/testit_api_client/model_utils.py", line 189, in __setattr__
    self[attr] = value
    ~~~~^^^^^^
  File "/usr/local/lib/python3.11/site-packages/testit_api_client/model_utils.py", line 510, in __setitem__
    self.set_attribute(name, value)
  File "/usr/local/lib/python3.11/site-packages/testit_api_client/model_utils.py", line 161, in set_attribute
    value = validate_and_convert_types(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/testit_api_client/model_utils.py", line 1632, in validate_and_convert_types
    input_value[index] = validate_and_convert_types(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/testit_api_client/model_utils.py", line 1582, in validate_and_convert_types
    converted_instance = attempt_convert_item(
                         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/testit_api_client/model_utils.py", line 1471, in attempt_convert_item
    raise conversion_exc
  File "/usr/local/lib/python3.11/site-packages/testit_api_client/model_utils.py", line 1462, in attempt_convert_item
    return deserialize_model(input_value, valid_class,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/testit_api_client/model_utils.py", line 1376, in deserialize_model
    return model_class._new_from_openapi_data(**kw_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/testit_api_client/model_utils.py", line 48, in wrapped_init
    return fn(_self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/testit_api_client/model_utils.py", line 371, in _new_from_openapi_data
    return cls._from_openapi_data(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/testit_api_client/model_utils.py", line 48, in wrapped_init
    return fn(_self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/testit_api_client/model/link_put_model.py", line 196, in _from_openapi_data
    setattr(self, var_name, var_value)
  File "/usr/local/lib/python3.11/site-packages/testit_api_client/model_utils.py", line 189, in __setattr__
    self[attr] = value
    ~~~~^^^^^^
  File "/usr/local/lib/python3.11/site-packages/testit_api_client/model_utils.py", line 510, in __setitem__
    self.set_attribute(name, value)
  File "/usr/local/lib/python3.11/site-packages/testit_api_client/model_utils.py", line 161, in set_attribute
    value = validate_and_convert_types(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/testit_api_client/model_utils.py", line 1582, in validate_and_convert_types
    converted_instance = attempt_convert_item(
                         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/testit_api_client/model_utils.py", line 1457, in attempt_convert_item
    raise get_type_error(input_value, path_to_item, valid_classes,
testit_api_client.exceptions.ApiTypeError: Invalid type for variable 'type'. Required value type is LinkType and passed type was NoneType at ['received_data']['links'][0]['type']`

А вызвано это тем что, в файле importer.py в методе "def __form_links(allure_links):" мы ожидаем тип линка написанный с большой буквы.
Написанный код:
`if 'type' in link and link['type'] in (
                        'Related', 'BlockedBy', 'Defect', 'Issue', 'Requirement', 'Repository'):
                    links[-1]['type'] = link['type']`

**Comment by PavelButuzov** [comment]
Добрый день!
Исправления доступны в версии импортера 1.4.1.
Большое вам спасибо за вашу помощь в улучшении функционала!

**Comment by ABolikov** [comment]
@PavelButuzov
