### ISSUE TITLE
Проблем с импортом тестов

### ISSUE THREAD

**Issue by Ammeleon** [testit-tms/importers#69]
Во время импорта ловлю ошибку:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python312\Scripts\testit.exe\__main__.py", line 7, in <module>
  File "C:\Python312\Lib\site-packages\testit_importer_allure\__main__.py", line 21, in console_main
    importer.send_result()
  File "C:\Python312\Lib\site-packages\testit_importer_allure\importer.py", line 64, in send_result
    autotest_id = self.__api_client.create_autotest(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\testit_importer_allure\apiclient.py", line 62, in create_autotest
    response = self.__autotest_api.create_auto_test(create_auto_test_request=model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\testit_api_client\api\auto_tests_api.py", line 1970, in create_auto_test
    return self.create_auto_test_endpoint.call_with_http_info(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\testit_api_client\api_client.py", line 881, in call_with_http_info
    return self.api_client.call_api(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\testit_api_client\api_client.py", line 423, in call_api
    return self.__call_api(resource_path, method,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\testit_api_client\api_client.py", line 205, in __call_api
    raise e
  File "C:\Python312\Lib\site-packages\testit_api_client\api_client.py", line 198, in __call_api
    response_data = self.request(
                    ^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\testit_api_client\api_client.py", line 469, in request
    return self.rest_client.POST(url,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\testit_api_client\rest.py", line 274, in POST
    return self.request("POST", url,
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\testit_api_client\rest.py", line 233, in request
    raise ApiException(http_resp=r)
testit_api_client.exceptions.ApiException: Status Code: 400
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Date': 'Fri, 18 Oct 2024 13:51:49 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '284', 'Connection': 'keep-alive', 'Access-Control-Allow-Origin': '*', 'X-Correlation-Id': '8b257487-4254-49ae-8106-e1ebe9bd6594', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains'})
HTTP response body: {"errors":{"Classname":["Class name cannot be empty or contain only white space characters"]},"type":"https://tools.ietf.org/html/rfc7231#section-6.5.1","title":"One or more validation errors occurred.","status":400,"traceId":"00-d7d796e29266c349f8a19b260a4483f2-c79aaaa8ce4d3c07-00"}

Не все тесты импортируются

**Comment by Ammeleon** [comment]
Дополню для testit 4.4.4 перебрал все релизы importer, в итоге корректно отрабатывает версия 1.6
Поправьте пожалуйста документацию, а именно таблицу версий в readme

**Comment by taipoxinous** [comment]
Спасмбо! Закрываю ошибку за неактуальностью проблемы. Версию поправим.
